<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="vyrazu66-ThinkCentre-M70t" failures="1" tests="2" name="Testng.ExceptionTimeOutTest" time="0.018" errors="0" timestamp="27 Jul 2023 10:54:08 GMT">
  <testcase classname="Testng.ExceptionTimeOutTest" name="infiniteloopTest" time="0.015">
    <failure message="
Expected exception java.lang.NumberFormatException but got org.testng.TestException: 
Expected exception java.lang.NumberFormatException but got org.testng.internal.thread.ThreadTimeoutException: Method org.testng.internal.TestNGMethod.infiniteloopTest() didn&#039;t finish within the time-out 2" type="org.testng.TestException">
      <![CDATA[org.testng.TestException: 
Expected exception java.lang.NumberFormatException but got org.testng.TestException: 
Expected exception java.lang.NumberFormatException but got org.testng.internal.thread.ThreadTimeoutException: Method org.testng.internal.TestNGMethod.infiniteloopTest() didn't finish within the time-out 2
	at org.testng.internal.Invoker.handleInvocationResults(Invoker.java:1503)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1251)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:51)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:85)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1197)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1122)
	at org.testng.TestNG.run(TestNG.java:1030)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: org.testng.TestException: 
Expected exception java.lang.NumberFormatException but got org.testng.internal.thread.ThreadTimeoutException: Method org.testng.internal.TestNGMethod.infiniteloopTest() didn't finish within the time-out 2
	at org.testng.internal.Invoker.handleInvocationResults(Invoker.java:1503)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:764)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:907)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1237)
	... 16 more
Caused by: org.testng.internal.thread.ThreadTimeoutException: Method org.testng.internal.TestNGMethod.infiniteloopTest() didn't finish within the time-out 2
	at java.base@17.0.5/java.lang.String.getChars(String.java:1677)
	at java.base@17.0.5/java.io.BufferedWriter.write(BufferedWriter.java:229)
	at java.base@17.0.5/java.io.Writer.write(Writer.java:249)
	at java.base@17.0.5/java.io.PrintStream.writeln(PrintStream.java:720)
	at java.base@17.0.5/java.io.PrintStream.println(PrintStream.java:1028)
	at app//Testng.ExceptionTimeOutTest.infiniteloopTest(ExceptionTimeOutTest.java:13)
	at java.base@17.0.5/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base@17.0.5/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base@17.0.5/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base@17.0.5/java.lang.reflect.Method.invoke(Method.java:568)
	at app//org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at app//org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:46)
	at app//org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:33)
	at java.base@17.0.5/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base@17.0.5/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base@17.0.5/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base@17.0.5/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base@17.0.5/java.lang.Thread.run(Thread.java:833)
]]>
    </failure>
  </testcase> <!-- infiniteloopTest -->
  <testcase classname="Testng.ExceptionTimeOutTest" name="test1" time="0.003"/>
</testsuite> <!-- Testng.ExceptionTimeOutTest -->
